version: '3'

services:

  kafka:
    image: lensesio/fast-data-dev:2.5.1-L1
    container_name: kafka
    restart: always
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    networks:
      - infrastructure

  mongo:
    image: mongo:4.4.1-bionic
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./.docker/mongo:/data/db"
    networks:
      - infrastructure
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD

  postgres:
    image: postgres:12.4-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./.docker/postgres:/var/lib/postgresql/data"
    networks:
      - infrastructure
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  
  redis:
    image: redis:6.2.1-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

networks:
  infrastructure: 

