version: '3'

services:

  kafka:
    build: ./kafka
    container_name: kafka
    restart: always
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    networks:
      - infrastructure

  mongo:
    build: ./mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./.docker/mongo:/data/db"
    networks:
      - infrastructure
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD

  postgres:
    build: ./postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./.docker/postgres:/var/lib/postgresql/data"
    networks:
      - infrastructure
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

networks:
  infrastructure: 

